# Generated by Django 4.1 on 2023-04-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "Email `email_repetido` already taken."},
                max_length=127,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "Username `usuario_repetido` already taken."},
                max_length=127,
                unique=True,
            ),
        ),
    ]
