# Generated by Django 4.1 on 2023-04-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_email_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "This field must be unique."},
                max_length=127,
                unique=True,
            ),
        ),
    ]
