# Generated by Django 4.1 on 2023-04-26 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_email_alter_user_username"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
    ]
