# Generated by Django 4.1 on 2023-04-27 16:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_movie_budget_movie_duration_movie_overview_and_more"),
        ("genres", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="genre",
            name="movies",
            field=models.ManyToManyField(related_name="genres", to="movies.movie"),
        ),
        migrations.AddField(
            model_name="genre",
            name="name",
            field=models.CharField(default=None, max_length=127, unique=True),
        ),
        migrations.AlterField(
            model_name="genre",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
