# Generated by Django 4.1 on 2023-04-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genres", "0002_genre_movies_genre_name_alter_genre_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=127, unique=True),
        ),
    ]
