# Generated by Django 4.1 on 2023-04-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genres", "0003_alter_genre_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=127),
        ),
    ]
