# Generated by Django 4.1 on 2023-04-27 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="budget",
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12),
        ),
        migrations.AddField(
            model_name="movie",
            name="duration",
            field=models.DurationField(default=None),
        ),
        migrations.AddField(
            model_name="movie",
            name="overview",
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name="movie",
            name="premiere",
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name="movie",
            name="title",
            field=models.CharField(default=None, max_length=127),
        ),
        migrations.AddField(
            model_name="movie",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
