# Generated by Django 4.1 on 2023-04-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_movie_budget_movie_duration_movie_overview_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="overview",
            field=models.TextField(default=None, null=True),
        ),
    ]
