# Generated by Django 4.1 on 2023-04-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_alter_movie_duration_alter_movie_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="premiere",
            field=models.DateField(),
        ),
    ]
